name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: true

jobs:
  fmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
          toolchain: nightly
      - run: cargo +nightly fmt --all -- --check
  test:
    runs-on: ubuntu-24.04
    needs: fmt
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@cargo-hack
      - run: cargo hack test --all-targets --feature-powerset
  docs:
    runs-on: ubuntu-24.04
    needs: fmt
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@cargo-hack
      - run: RUSTDOCFLAGS="-Dwarnings" cargo hack doc --document-private-items --no-deps --feature-powerset
  clippy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-2022
          - macos-15
          - ubuntu-24.04
    needs: fmt
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - uses: taiki-e/install-action@cargo-hack
      - run: cargo hack clippy --all-targets --feature-powerset
