name: scheduled

on:
  schedule:
    - cron: "43 13 12 * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: true

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - uses: taiki-e/install-action@cargo-hack
      - run: cargo hack test --all-targets --feature-powerset
  update:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@cargo-hack
      - run: cargo update
      - run: cargo hack test --all-targets --feature-powerset
